### ISSUE TITLE
Multiple network aliases don't work with busybox breaking the QLever example

### ISSUE THREAD

**Issue by niklas88** [ad-freiburg/gantry#9]
When trying to run the [QLever E2E example](/ad-freiburg/gantry/tree/master/examples/qlever_e2e) the `qlever` service is not reachable under the name `qlever` in the `wait_for` step. 

Using the `command: "waitfor http://qlever_e2e_qlever:7001"` instead seems to work. 

However in the `run_queries` step `http://qlever` does work. The root cause seems to be a limitation in the `busybox` containers host lookup with multiple network aliases. Switching the first line in the `Dockerfile` to `FROM alpine` lets the example run through. Though that isn't exactly a bug in gantry I think we should make sure that the first alias passed to `cocker` is the canonical one that users will use in their files. This would reduce confusion.

**Comment by niklas88** [comment]
I think since it also makes the `wait_for` code nicer we should switch it to alpine especially since I'm not sure if docker keeps the order of aliases.

**Comment by niklas88** [comment]
Ok I just figured out that you do set them in the correct order, still somehow for the QLever E2E example the aliases in `docker inspect` are
```
"Aliases": [
                        "qlever_e2e_qlever",
                        "qlever",
                        "3b5a1ed18f92"
                    ]
```

**Comment by lehmann-4178656ch** [comment]
With the next pull all `busybox` based images will migrate to `alpine` as `alpine` did not display the behavior mentioned in this issue. The cause for this issue is that in the environment a seperate host `qlever` exists and `alpine` handles this situation quite well by using the provided aliases first but `busybox` fails to do so and searches in the network first.
